project:
  type: book
  output-dir: docs

book:
  title: "Uso de R para toma de decisiones en salud"
  author: "Rodrigo Zepeda Tello"
  date: today
  chapters:
    - index.qmd
    - instalar.qmd
    - modelos.qmd
    - ejemplomodelo.qmd
    - datos.qmd
    - paquetes.qmd
    - references.qmd

options:
  engine: knitr
  
bibliography: references.bib

format:
  html:
    theme: sandstone
  pdf:
    documentclass: scrreprt



